# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [16]:
import numpy as np
# listt = [1, 2, 3, 4]
# arr = np.array(listt)

# arr = arr % 2
arr = np.arange(20).reshape(5, 4)
print(arr[2::])

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [25]:
# Task 1
arr = np.random.uniform(0,20,[4, 7])
print(arr)
arr = (arr - arr.min()) / (arr.max() - arr.min())
print(arr.max())
print(arr.min())
print(arr)

[[14.29403699  7.92074913 12.0903714   6.10503358  2.49483039 19.2511923
  10.34453591]
 [ 4.68904     2.28319924  4.91600322 18.47132513  6.70959681 11.04471642
  19.61107612]
 [12.26693221 14.63491813 19.93987905  9.8984281   4.26697498 14.26446983
  16.53408741]
 [18.97710667  1.40404225 18.38545765  5.88666745  6.06877556  0.4925469
   6.15419231]]
1.0
0.0
[[0.70968552 0.3819651  0.59637098 0.28859931 0.10295929 0.96458708
  0.50659849]
 [0.2157876  0.09207702 0.22745826 0.92448558 0.31968652 0.54260242
  0.98309265]
 [0.6054499  0.72721395 1.         0.4836592  0.19408462 0.70816515
  0.82487101]
 [0.95049334 0.04686994 0.9200702  0.27737072 0.28673489 0.
  0.2911271 ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [45]:
arr = np.random.randint(0,10, [8, 10])
# print(arr)
ind = arr.sum(axis=1).argmin() # строки
print(ind+1, arr[ind])




3 [8 2 0 1 5 5 5 0 0 0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [44]:
a = np.array([1, 2])
b = np.array([3, 4])
np.linalg.norm(a - b)

2.8284271247461903

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [46]:
A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]
B = [[3, -1], [2, 1]]
C = [[7, 21], [11, 8], [8, 4]]


# X = A^-1 * -C * B^-1

print(np.linalg.matrix_power(A, -1))


[[ 0.2 -0.4 -0. ]
 [-0.6  2.2 -2. ]
 [ 0.6 -1.2  1. ]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.