# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [24]:
import numpy as np
# listt = [1, 2, 3, 4]
# arr = np.array(listt)

# arr = arr % 2
arr = np.arange(20).reshape(5, 4)
print(arr[2::])

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [25]:
# Task 1
arr = np.random.uniform(0,20,[4, 7])
print(arr)
arr = (arr - arr.min()) / (arr.max() - arr.min())
print(arr.max())
print(arr.min())
print(arr)

[[19.90925124 18.15058069  5.41086846 12.08818644  4.3241916  14.72113502
  12.21244686]
 [18.96511635 18.22569965 10.8119539   9.91511214  7.09144815  3.2031005
   3.16373164]
 [ 5.72483119 11.11242963  3.17208145 19.68524867  9.24008854 15.90527869
  12.99089659]
 [ 3.69362647  4.29088754 18.52956449 16.0840024  11.81601196 11.18849107
  17.65813933]]
1.0
0.0
[[1.00000000e+00 8.94976651e-01 1.34193317e-01 5.32945827e-01
  6.92997285e-02 6.90178845e-01 5.40366345e-01]
 [9.43618657e-01 8.99462565e-01 4.56732454e-01 4.03175337e-01
  2.34553278e-01 2.35100830e-03 0.00000000e+00]
 [1.52942375e-01 4.74676103e-01 4.98629144e-04 9.86623134e-01
  3.62864637e-01 7.60892905e-01 5.86853390e-01]
 [3.16439762e-02 6.73108945e-02 9.17608603e-01 7.71565832e-01
  5.16692257e-01 4.79218299e-01 8.65569301e-01]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [26]:
arr = np.random.randint(0,10, [8, 10])
# print(arr)
ind = arr.sum(axis=1).argmin() # строки
print(ind+1, arr[ind])




1 [1 1 3 1 5 0 1 4 0 0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [27]:
a = np.array([1, 2])
b = np.array([3, 4])
np.linalg.norm(a - b)

2.8284271247461903

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [28]:
A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]
B = [[3, -1], [2, 1]]
C = [[7, 21], [11, 8], [8, 4]]


# X = A^-1 * -C * B^-1



## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [29]:
import numpy as np
data = np.loadtxt("./minutes_n_ingredients.csv",int,delimiter=",",skiprows=1)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [30]:
print(f"Мин: {np.min(data[:, 1])}\nМакс: {np.max(data[:, 1])}\nМедиана: {np.median(data[:, 1])}")
print(f"Мин: {np.min(data[:, 2])}\nМакс: {np.max(data[:, 2])}\nМедиана: {np.median(data[:, 2])}")

Мин: 0
Макс: 2147483647
Медиана: 40.0
Мин: 1
Макс: 39
Медиана: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [31]:
quan = 0.75
val = data[:, 1] <= np.quantile(data[:, 1], quan)
print(data[val])


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [32]:
print(f"Кол-во: {np.sum(data[:, 1] == 0)}")
arr = np.copy(data)
arr[:, 1][arr[:, 1] == 0] = 1 # замена строк на единицу
# print(np.sum(arr[:, 1] == 0))


Кол-во: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [33]:
uniq = np.unique(data, axis=1)
print(uniq.shape)

(100000, 3)


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?


In [34]:
unique, amount = np.unique(data[:, 2], return_counts=True)
print(f"Кол-во: {amount.size}")
print(dict(zip(amount,unique)))

Кол-во: 37
{13: 1, 926: 2, 2895: 3, 5515: 4, 7913: 5, 9376: 6, 10628: 7, 10951: 8, 10585: 9, 9591: 10, 8297: 11, 6605: 12, 4997: 13, 3663: 14, 2595: 15, 1767: 16, 1246: 17, 790: 18, 573: 19, 376: 20, 217: 21, 161: 22, 105: 23, 69: 24, 50: 25, 28: 26, 16: 28, 12: 30, 3: 35, 1: 39, 2: 33}


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [35]:
new_arr = data[data[:, 2] < 6]
print(new_arr)


[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [42]:
# Не понятно, что делать с divide by zero
without_zero_arr = data.copy()


mask = without_zero_arr[:, 1] == 0
without_zero_arr[:, 1][mask] = 1

val = (without_zero_arr[:,2]/(without_zero_arr[:,1]))
print(f"Макс значение: {np.max(val)}")

Макс значение: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [37]:
amount = 100
arr = data[data[:, 1].argsort()][::-1][:amount] # 100 рецептов
print(np.sum(arr[:, 2])/amount)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [38]:
print(data[np.random.randint(len(data), size=10)])

[[139008     15      6]
 [458215     55     13]
 [283453     50      4]
 [222363     15      9]
 [ 34387     50      9]
 [ 57947     80     11]
 [200079     45      7]
 [ 55748     25      6]
 [436690     40     10]
 [408186      5      3]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [39]:
avg = np.mean(data[:, 2])
print(avg)
arr = data[data[:, 2] < avg]
print(f"{len(arr)*100/len(data)}%")

9.05528
58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [40]:
new_arr = np.copy(data)
arr = np.c_[data, (new_arr[:, 1] <= 20) & (new_arr[:, 2] <= 5)]
print(arr)


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [41]:
arr_len = arr.shape[0]
rec_len = len(arr[arr[:, 3] == 1])

print(f"{rec_len*100/arr_len}%")

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.