# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [247]:
import numpy as np
# listt = [1, 2, 3, 4]
# arr = np.array(listt)

# arr = arr % 2
arr = np.arange(20).reshape(5, 4)
print(arr[2::])

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [248]:
# Task 1
arr = np.random.uniform(0,20,[4, 7])
print(arr)
arr = (arr - arr.min()) / (arr.max() - arr.min())
print(arr.max())
print(arr.min())
print(arr)

[[17.89368527 14.87468774  3.91108101 17.0024749   8.72527072  4.03785599
   0.43849641]
 [19.83302325 18.57934362  3.97124717 12.93798282 18.84355947  5.44764488
   1.06706058]
 [ 6.89143684 16.55173495  2.70849663 11.49871058  5.39875964  1.42373905
   0.79013839]
 [ 4.58525011  9.86619897  8.88779988  9.23980392  6.63997441  7.9408852
   2.18961289]]
1.0
0.0
[[0.90000591 0.74434357 0.17904972 0.85405427 0.42727386 0.18558636
  0.        ]
 [1.         0.9353591  0.18215194 0.64448525 0.94898232 0.25827639
  0.03240936]
 [0.33271966 0.8308137  0.11704334 0.57027502 0.25575583 0.05080004
  0.01813099]
 [0.21381051 0.48610119 0.43565401 0.45380367 0.31975402 0.3868302
  0.09028921]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [249]:
arr = np.random.randint(0,10, [8, 10])
# print(arr)
ind = arr.sum(axis=1).argmin() # строки
print(ind+1, arr[ind])




6 [0 8 5 3 7 3 5 0 1 2]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [250]:
a = np.array([1, 2])
b = np.array([3, 4])
np.linalg.norm(a - b)

2.8284271247461903

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [251]:
A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]
B = [[3, -1], [2, 1]]
C = [[7, 21], [11, 8], [8, 4]]


# X = A^-1 * -C * B^-1



## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [252]:
import numpy as np
data = np.loadtxt("./minutes_n_ingredients.csv",int,delimiter=",",skiprows=1)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [253]:
print(f"Мин: {np.min(data[:, 1])}\nМакс: {np.max(data[:, 1])}\nМедиана: {np.median(data[:, 1])}")
print(f"Мин: {np.min(data[:, 2])}\nМакс: {np.max(data[:, 2])}\nМедиана: {np.median(data[:, 2])}")

Мин: 0
Макс: 2147483647
Медиана: 40.0
Мин: 1
Макс: 39
Медиана: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [254]:
quan = 0.75
val = data[:, 1] <= np.quantile(data[:, 1], quan)
print(data[val])


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [265]:
print(f"Кол-во: {np.sum(data[:, 1] == 0)}")
arr = np.copy(data)
arr[:, 1][arr[:, 1] == 0] = 10 # замена строк на единицу
# print(np.sum(arr[:, 1] == 0))


Кол-во: 479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [256]:
uniq = np.unique(data, axis=1)
print(uniq.shape)

(100000, 3)


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?


In [257]:
unique, amount = np.unique(data[:, 2], return_counts=True)
print(f"Кол-во: {amount.size}")
print(dict(zip(amount,unique)))

Кол-во: 37
{13: 1, 926: 2, 2895: 3, 5515: 4, 7913: 5, 9376: 6, 10628: 7, 10951: 8, 10585: 9, 9591: 10, 8297: 11, 6605: 12, 4997: 13, 3663: 14, 2595: 15, 1767: 16, 1246: 17, 790: 18, 573: 19, 376: 20, 217: 21, 161: 22, 105: 23, 69: 24, 50: 25, 28: 26, 16: 28, 12: 30, 3: 35, 1: 39, 2: 33}


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [258]:
new_arr = data[data[:, 2] < 6]
print(new_arr)


[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [259]:
# Не понятно, что делать с divide by zero
val = (data[:,2]/(data[:,1]!= 0))
print(val)
print(np.max(val))

[16.  7.  6. ... 15.  4. 14.]
inf


/Users/user/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [260]:
amount = 100
arr = data[data[:, 1].argsort()][::-1][:amount] # 100 рецептов
print(np.sum(arr[:, 2])/amount)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [261]:
print(data[np.random.randint(len(data), size=10)])

[[ 76070     10     13]
 [ 71725     20     10]
 [307260     17      8]
 [146563      7      5]
 [361604      5      2]
 [273593    300     15]
 [133019    140      8]
 [423164     15      3]
 [ 29129     48     15]
 [189987     75      9]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [262]:
avg = np.mean(data[:, 2])
print(avg)
arr = data[data[:, 2] < avg]
print(f"{len(arr)*100/len(data)}%")

9.05528
58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [263]:
new_arr = np.copy(data)
arr = np.c_[data, (new_arr[:, 1] <= 20) & (new_arr[:, 2] <= 5)]
print(arr)


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [264]:
arr_len = arr.shape[0]
rec_len = len(arr[arr[:, 3] == 1])

print(f"{rec_len*100/arr_len}%")

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.